### ISSUE TITLE
Nomenclature Doesn't Render

### ISSUE THREAD

**Issue by devoncward** [BYU-Engineering/thesis_template#12]
In the example template, the nomenclature page does not render, when using overleaf, Texmaker, miketex, etc.

**Comment by jgoeders** [comment]
@devoncward I haven't had a chance to look at this one yet, but I'll try and get to it this week.

**Comment by jgoeders** [comment]
I've included below what chatgpt told me about the nomenclature package.  Basically, you need to run an extra step to build the required nomenclature file, and then re-run your latex compile.

I do my LaTeX editing in VS Code using LaTeX Workshop.  Under the hood, this uses latexmk, which is a popular tool to build LaTeX projects.  I found [this page](https://tex.stackexchange.com/a/105978/16483) that explains how to configure your latexmk software to run the nomenclature build as part of the full build process.  I'm not sure why your overleaf isn't handling this properly as part of the build process as [this page](https://www.overleaf.com/learn/latex/Nomenclatures) seems to suggest it should handle it properly.  I would check the compiler log for errors or warnings.

FYI - as part of PR #16, I now ensure nomenclature is run as part of our testing on the template repository.  I use latexmk with the configuration file [here](https://github.com/BYU-Engineering/thesis_template/blob/main/.github/.latexmkrc).


## Chat GPT answer:

When LaTeX generates a document with a nomenclature section, it relies on an external tool to sort and create the nomenclature list, which is then included in the final document. If you're seeing the message "No file template.nls" it means the process to generate the nomenclature list was not completed successfully. Here's how to fix this and ensure your nomenclature prints correctly:

### Step 1: Include the Nomenclature in Your LaTeX Document

First, ensure your LaTeX document is set up correctly for nomenclature. You need to include the `nomencl` package and configure it. Here is a basic setup:

```latex
\documentclass{article}
\usepackage{nomencl}
\makenomenclature

\begin{document}

\mbox{}

\nomenclature{N}{Number of turns}
\nomenclature{$\alpha$}{Angle of friction}

\printnomenclature

\end{document}
```

### Step 2: Generate the Nomenclature

After compiling your LaTeX document once with `pdflatex` (or `latex`, `xelatex`, etc., depending on your workflow), you need to generate the nomenclature list. The message "No file template.nls" suggests this step was either not done or not successful. 

To generate the nomenclature, you use the `makeindex` command in the terminal or command prompt. Assuming your LaTeX file is named `template.tex`, the command would look something like this:

```sh
makeindex template.nlo -s nomencl.ist -o template.nls
```

This command tells `makeindex` to process the `.nlo` file generated by the `nomencl` package, using the `nomencl.ist` style file, and to output the `.nls` file needed for the nomenclature list.

### Step 3: Recompile Your LaTeX Document

After generating the `.nls` file, recompile your LaTeX document with `pdflatex` (or your LaTeX engine of choice) to incorporate the nomenclature list into your document:

```sh
pdflatex template.tex
```

### Troubleshooting

- **Command Not Found:** If the `makeindex` command is not found, ensure you have a complete LaTeX installation. Some minimal installations might not include all tools.
- **Still No Nomenclature:** If the nomenclature still doesn't appear, double-check your document's setup and ensure you're following all steps in the correct order.
- **Automation:** Some LaTeX editors and IDEs can automate this process. Check if yours supports custom build steps or has specific support for nomenclature.

Following these steps should resolve the issue and allow your nomenclature to print correctly in the document.
