### ISSUE TITLE
Table of Contents not included in Table of Contents

### ISSUE THREAD

**Issue by devoncward** [BYU-Engineering/thesis_template#19]
In the template, the table of contents is not included in the table of contents page.  To my understanding, it should be. 

![image](https://github.com/BYU-Engineering/thesis_template/assets/2983314/d014ab7f-41fc-4ee0-808c-de7eebd02628)

**Comment by BYU-Engineering-ADR** [comment]
This is as intended. It may have been a BYU Grad Studies requirement in the past, but it is not common to do this (I can't think of a functional reason for doing it). The ToC should only include things that come after it. (Note that it does not include your abstract or acknowledgements either.) Thanks for your suggestion.
