### ISSUE TITLE
ETD Feedback

### ISSUE THREAD

**Issue by jvbroek** [BYU-Engineering/thesis_template#3]
I am in the process of getting my ETD approved right now, here is some of the feedback I've received that they requested I change:

"Masters of Science" -> "Master of Science" on the title and custom title pages.

On the first (non-custom) title page, the title MUST be in inverted pyramid.  I don't think the format here needs to change, but a comment would be nice.

The custom title page is supposed to have a bookmark.

None of these changes are particularly huge or a big deal, but I thought it would be nice to match the template to the university requirements to avoid the need for tinkering after submission.

**Comment by jvbroek** [comment]
One final requested change: the table of contents should also be bookmarked.

**Comment by jgoeders** [comment]
> The custom title page is supposed to have a bookmark.

> One final requested change: the table of contents should also be bookmarked.

These seem to be fixed already.

> On the first (non-custom) title page, the title MUST be in inverted pyramid. I don't think the format here needs to change, but a comment would be nice.

There is a comment there now.
