### ISSUE TITLE
Nomencl Workaround for Latex Workshop Users with a Separate Out Dir

### ISSUE THREAD

**Issue by hrjs84** [BYU-Engineering/thesis_template#4]
I had an issue where the nomenclature section of the template would not compile. After a day of researching, these steps worked on my setup. Sharing to spread awareness, hopefully a better solution can be found :) YMMV

## A fix for using nomencl with the [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop) extension for VS Code with an outDir:

    Edit the file /usr/share/texlive/texmf-dist/web2c/texmf.cnf as root/administrator.
    Search for openout_any=p (this is the paranoid mode)
    Replace by openout_any=r or openout_any=a.
This is needed for makeindex and pdflatex to accept your out subdirectory as valid.

VS Code -> Preferences -> Settings -> Latex:Out Dir -> Change:
```
%DIR%/.out
```
Name your out directory.

VS Code -> Preferences -> Settings -> Latex:Auto Build:Run -> Change:
```
onSave
```
Without this, the auto build kept re-running forever for some reason.

VS Code -> Preferences -> Settings -> Latex:Tools -> Edit .JSON -> Add:
```
{ 
        "name": "makeindex",
        "command": "makeindex",
        "args": [
            "%OUTDIR%/%DOCFILE%.nlo",
            "-s",
            "nomencl.ist",
            "-o",
            "%OUTDIR%/%DOCFILE%.nls"
        ]
    },
```
This generates the necessary .nls file.

Edit:
```
{
        "name": "pdflatex",
        "command": "pdflatex",
        "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory",
            "%OUTDIR%",
            "%DOC%"
        ],
        "env": {}
    },
```
This tells pdflatex to send outputs to your out directory, where makeindex and latexmk are looking.

VS Code -> Preferences -> Settings -> Latex:Recipes -> Edit .JSON -> Add:
```
{
        "name": "pdflatex ➞ makeindex ➞ latexmk",
        "tools": [
            "pdflatex",
            "makeindex",
            "latexmk"
        ]
    },
```
This is the toolchain that compiles the template files such that they match the given pdfs.

Except that my "Appendices" page does not have the "17" page number. Not sure about that one...

**Comment by jgoeders** [comment]
Thanks for documenting this.  I'm going to close the issue now.
