### ISSUE TITLE
Appendices Page Number Fix

### ISSUE THREAD

**Issue by hrjs84** [BYU-Engineering/thesis_template#5]
In the example document, the appendices divider page is numbered. To achieve this, the following change must be made to the `byuthesis.cls` file:

Line 172: `\aliaspagestyle{part}{plain}`

Between this and the nomencl fix I documented, the document I compile from the source code matches the given example exactly.

**Comment by hrjs84** [comment]
I should mention that this is for the template_twosided example, the given template example is also missing this page number. I believe the page number should be included in both versions, since it's numbered in the ToC.

**Comment by BYU-Engineering-ADR** [comment]
The intent was for the appendix page divider to not be numbered just for aesthetic reasons alone. However, this is a matter of personal preference.

**Comment by cgoates** [comment]
FWIW, I was also asked to add a page number by the Civil Engineering department in order to have my dissertation approved. So while it may be a matter of opinion, it appears that it may be required, at least by some of the departments.

**Comment by BYU-Engineering-ADR** [comment]
@cgoates Thanks for this notification. This appendix page number is not an issue with the college or university. Departments, however, can make up their own rules as long as they don't violate university or college rules, which are well documented. But I doubt if this is a written rule in CCE -- just something that the person checking dissertation formats in CCE has decided to enforce.
