### ISSUE TITLE
Citations not found using default bibliography engine

### ISSUE THREAD

**Issue by kendrickshepherd** [BYU-Engineering/thesis_template#8]
Is there a reason that biber is chosen as the preferred compilation backend for the references? bibtex also appears to work and is perhaps more stable/widely used. Honestly, I don't care too much except a student and I just spent a significant amount of time on this, only to find that biber wasn't operating successfully in out machines, but bibtex was.

Alternatively, could some documentation be given about potential errors in building the references and pointing people to try using bibtex instead? Thanks for this.

**Comment by jgoeders** [comment]
There is a great explanation about the different tools here: https://tex.stackexchange.com/a/25702  

Bibtex is very old and not actively developed.  Most modern environments have moved to biblatex, which has support for modern citation styles, unicode characters, and has many other helpful features.  Biblatex uses biber to process the bibliography files, which is why your system needs that installed.

Can you provide more about the error you were running into with biber and how you resolved it?  It might help others in the future.

**Comment by jgoeders** [comment]
Also, if you are on an ubuntu system, you may find this list if necessary apt packages helpful: https://github.com/BYU-Engineering/thesis_template/blob/3f555e3a96835f9fa30651de3e3b3b177cebc4f7/.github/workflows/test.yml#L8

**Comment by kendrickshepherd** [comment]
Thanks for the explanation. I also found that stackexchange article earlier, and it was indeed very helpful.

I am using a Mac (Ventura 13.3) in connection with TeXShop. Biber is installed on my machine, but it is not the default BibTeX engine, and never before have I needed to change this engine to compile references. Nonetheless, when changing the default engine to biber, the compiler works correctly (albeit slowly, and without any prompt until after a sizable lagtime). When attempting to compile the bibliography before, using bibtex, I got the following error:

_This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: template.aux
I found no \citation commands---while reading file template.aux
I found no \bibdata command---while reading file template.aux
I found no \bibstyle command---while reading file template.aux
(There were 3 error messages)_

Digging deeper into the log file gives the following prompt:

_Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                template
(biblatex)                and rerun LaTeX afterwards._

However, when keeping the default compiler for the bibliography as bibtex and changing the byuthesis.cls file in the following places, I was able to successfully build the thesis templates (both fancy and simple).

Line 332: 
change \usepackage[backend=biber,style=ieee,doi=true]{biblatex}
to 	
\usepackage[backend=bibtex,style=ieee,doi=true]{biblatex}

Line ~582:
add the flag 
backend=bibtex
to the list of inputs for the biblatex package

**Comment by BYU-Engineering-ADR** [comment]
Kendrick,

I’m sorry for the trouble that you’ve had and the time you’ve spent getting the template to work on your machine.  I’m on a Macbook Pro (Ventura 13.5.2) and have compiled the thesis template document with TexPad and TeXShop without any needed changes to my LaTeX installation. I’ve never had any of the errors or issues that you’ve described. I have also compiled the template in Overleaf and consider that to be a good baseline installation.

I switched to biblatex to get some of the desired features in the fancy version working – the biblatex documentation is detailed (not necessarily easy to follow) and biblatex provides advantages that Jeff outlined. Honestly, I didn’t think the backref option would work with bibtex as the backend (in the fancy option) – on that, I might be wrong.

Of course, you are welcome to use whatever bibliography package you prefer.

Tim

From: kendrickshepherd ***@***.***>
Date: Monday, November 6, 2023 at 8:32 PM
To: BYU-Engineering/thesis_template ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [BYU-Engineering/thesis_template] Citations not found (Issue #8)

Thanks for the explanation. I also found that stackexchange article earlier, and it was indeed very helpful.

I am using a Mac (Ventura 13.3) in connection with TeXShop. Biber is installed on my machine, but it is not the default BibTeX engine, and never before have I needed to change this engine to compile references. Nonetheless, when changing the default engine to biber, the compiler works correctly (albeit slowly, and without any prompt until after a sizable lagtime). When attempting to compile the bibliography before, using bibtex, I got the following error:

This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: template.aux
I found no \citation commands---while reading file template.aux
I found no \bibdata command---while reading file template.aux
I found no \bibstyle command---while reading file template.aux
(There were 3 error messages)

Digging deeper into the log file gives the following prompt:

Package biblatex Warning: Please (re)run Biber on the file:
(biblatex) template
(biblatex) and rerun LaTeX afterwards.

However, when keeping the default compiler for the bibliography as bibtex and changing the byuthesis.cls file in the following places, I was able to successfully build the thesis templates (both fancy and simple).

Line 332:
change \usepackage[backend=biber,style=ieee,doi=true]{biblatex}
to
\usepackage[backend=bibtex,style=ieee,doi=true]{biblatex}

Line ~582:
add the flag
backend=bibtex
to the list of inputs for the biblatex package

**Comment by kendrickshepherd** [comment]
Thanks, Tim and Jeff. I understand that there are simply differences between machines, not to mention operating systems.  The time debugging was not ill-spent: I learned a bit more about LaTeX and if anyone in the future faces the same problem, there's some documentation now about a potential solution.

Thanks for your help.
